### ISSUE TITLE
Emit more detailed meta for accurate state tracking

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#768]
Tracking detailed state changes is impossible with the current telemetry metadata. We need the original and subsequent state for operations that insert, update, or delete jobs for accurate information.

- [x] Include job details in meta for all `Engine` functions
- [x] Include per-queue counts for rescued and discarded in the Lifeline plugin
- [x] Include per-queue counts for deleted in the Pruner plugin
- [x] Include per-queue counts for staged in the Stager plugin

**Comment by sorentwo** [comment]
Closed with 738088d, 7565f6a, b72f095, daeb8e3
